# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. 
on:
  
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
     
  # This workflow contains a single job called "build"  
  build:
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Create a build matrix for your jobs
    strategy:
      matrix:
        node-version: [6.14.8]
      

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  
      # Setup Node.js environment 
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.nove-version }}
        
      # Install all dependencies  
      - run: npm install
      - run: npm install cypress

      # Run all tests
      - run: npm run cy:run:clean
        continue-on-error: true

      # Copy screenshots of tests failure
      - run: mkdir public
      - run: mkdir public/test-report
      - run: find ./test-report -type f -name '*.png' -exec mv {} ./public/test-report ';'

      # Generate mochawesome-report
      - run: npm run cy:generate:html:report

      # Deploy report in GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: github-pages
          FOLDER:  test-report
